#ifndef _OPENCAFFE_H
#define _OPENCAFFE_H

namespace OpenCaffe {

typedef enum {
    TEMP_HEATER = 0U,
    TEMP_STEAM_HEATER = 1U,
    BREW_UNIT_CURRENT = 2U,
    GRINDER_CURRENT = 3U,
    GRINDER_DUO_CURRENT = 4U,
    //UNUSED 3 channels 5, 6, 7

    BREW_UNIT_POSITION = 8U,
    MILK_CONTAINER_POSITION = 9U,
    CAPPUCCINATORE_POSITION = 10U,
    MULTIVALVE_POSITION = 11U,
    LIFTER_POSITION = 12U
}T_AnalogPort;

typedef enum {
    BREW_UNIT_PRESENT = 0U,
    WATERTANK_PRESENT = 1U,
    WATERTANK_EMPTY = 2U,
    DREG_DRAWER_PRESENT = 3U,
    DREG_DRAWER_FULL = 4U,
    DRIP_DRAWER_PRESENT = 5U,
    DRIP_DRAWER_FULL = 6U,
    DOOR_CLOSED = 7U,
    BEAN_CONTAINER_CLOSED = 8U,
    GRINDER_OVERVOLTAGE = 9U,
    GRINDER_DUO_OVERVOLTAGE = 10U,
    BREW_UNIT_OVERVOLTAGE = 11U,
    // UNUSED 4 channels 12, 13, 14, 15

    MILK_CONTAINER_PRESENT = 16U,
    MILK_DRAWER_PRESENT = 17U,
    CAPPUCCINATORE_MILK_POSITION = 18U,
    CAPPUCCINATORE_FOAM_POSITION = 19U,

    LIFTER_UP_BUTTON = 20U,
    LIFTER_DOWN_BUTTON = 21U
}T_DigitalInPort;

typedef enum {
    
}T_DigitalOutPort;

} //namespace OpenCaffe

#endif //_OPENCAFFE_H